kind: pipeline
type: kubernetes
name: default
host_aliases:
  - ip: 10.1.1.2
    hostnames:
     - git.lab.sorijen.net.au
steps:
  - name: dnsutils
    image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
    commands:
    - sleep
    - "infinity"
  - name: test
    image: registry-proxy.lab.sorijen.net.au/library/node:18
    commands:
    - npm i --location=global pnpm
    - pnpm install
    - pnpm test:all
