kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
pipeline:
  docker:
    image: plugins/docker
    custom_dns: [ 10.1.3.100 ]