kind: pipeline
type: kubernetes
name: default
steps:
  - name: test
    image: registry-proxy.lab.sorijen.net.au/library/node:18
    commands:
    - cd src/Hive.FrontEnd
    - npm i --location=global pnpm
    - pnpm install
    - pnpm test:all
