kind: pipeline
type: kubernetes
name: default
host_aliases:
  - ip: 10.1.1.2
    hostnames:
     - git.lab.sorijen.net.au
steps:
  - name: test
    image: registry-proxy.lab.sorijen.net.au/library/node:18
    commands:
    - curl -fsSL https://get.pnpm.io/install.sh | sh -
    - pnpm install
    - pnpm test:all
