kind: pipeline
type: kubernetes
name: testing
steps:
  - name: frontend
    image: registry-proxy.lab.sorijen.net.au/library/node:18-alpine
    commands:
      - cd src/Hive.FrontEnd
      - npm i --location=global pnpm
      - pnpm install
      - pnpm test:all
      - mv reports/* ${DRONE_WORKSPACE}/reports/
    volumes:
      - name: reports
        path: ${DRONE_WORKSPACE}/reports
  - name: domain
    image: mcr.microsoft.com/dotnet/sdk:8.0.100-preview.2
    commands:
      - dotnet new tool-manifest || true
      - dotnet tool install dotnet-reportgenerator-globaltool
      - dotnet test --collect:"XPlat Code Coverage" ./src/Hive.Domain.Tests -c Test --settings ./src/Hive.Domain.Tests/runsettings.xml
      - mkdir -p ./domain-coverage/
      - mv src/Hive.Domain.Tests/TestResults/**/coverage.opencover.xml ./domain-coverage/
      - cp ./domain-coverage/coverage.opencover.xml ${DRONE_WORKSPACE}/reports/domain-coverage.opencover.xml
      - mv ./domain-coverage/coverage.opencover.xml ./domain-coverage/domain-coverage.opencover.xml
      - dotnet reportgenerator "-reports:./domain-coverage/domain-coverage.opencover.xml" "-targetdir:${DRONE_WORKSPACE}/reports" -reporttypes:Html
    volumes:
      - name: reports
        path: ${DRONE_WORKSPACE}/reports
  - name: api
    image: mcr.microsoft.com/dotnet/sdk:8.0.100-preview.2
    commands:
      - dotnet new tool-manifest || true
      - dotnet tool install dotnet-reportgenerator-globaltool
      - dotnet test --collect:"XPlat Code Coverage" ./src/Hive.Api.Tests -c Test --settings ./src/Hive.Api.Tests/runsettings.xml
      - mkdir -p ./api-coverage/
      - mv src/Hive.Api.Tests/TestResults/**/coverage.opencover.xml ./api-coverage/
      - cp ./api-coverage/coverage.opencover.xml ${DRONE_WORKSPACE}/reports/api-coverage.opencover.xml
      - mv ./api-coverage/coverage.opencover.xml ./api-coverage/api-coverage.opencover.xml
      - dotnet reportgenerator "-reports:./api-coverage/api-coverage.opencover.xml" "-targetdir:${DRONE_WORKSPACE}/reports" -reporttypes:Html
    volumes:
      - name: reports
        path: ${DRONE_WORKSPACE}/reports
  - name: sonar
    image: registry.lab.sorijen.net.au/sonar-scanner:latest
    depends_on:
      - frontend
      - domain
      - api
    volumes:
      - name: reports
        path: ${DRONE_WORKSPACE}/reports
    environment:
      LANG: en_US.UTF-8
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
      SONARQUBE_KEY:
        from_secret: SONARQUBE_KEY
    commands:
      - sed -i "s~\.\./~Hive\.FrontEnd/~g" ${DRONE_WORKSPACE}/reports/__coverage__/lcov.info
      - sed -i "s~${WORKSPACE}/~~g" ${DRONE_WORKSPACE}/ops/SonarQube.Analysis.xml
      - node -v
      - dotnet new tool-manifest || true
      - dotnet tool install dotnet-sonarscanner
      - dotnet sonarscanner begin /k:hive /s:${DRONE_WORKSPACE}/ops/SonarQube.Analysis.xml /d:sonar.login=$SONARQUBE_KEY
      - dotnet build -c Test ./src
      - dotnet test ./src -c Test --collect:"XPlat Code Coverage" --settings ./src/Hive.Api.Tests/runsettings.xml
      - dotnet sonarscanner end /d:sonar.login=$SONARQUBE_KEY

volumes:
  - name: reports
    temp: { }
