kind: pipeline
type: kubernetes
name: default
host_aliases:
  - ip: 10.1.1.2
    hostnames:
     - git.lab.sorijen.net.au
steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world