stages:
- name: test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        curl  --retry 4 --retry-connrefused -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
        cd ./src/FrontEnd
        pnpm install
        pnpm test
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/sdk:latest
      shellScript: |-
        cd ./src
        dotnet test .\Api\Hive.Api.Tests -c Test  /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:SkipAutoProps=true  /p:ExcludeByAttribute="ExcludeFromCodeCoverage" /p:Exclude="[Hive.Domain]*"
        dotnet test .\Api\Hive.Domain.Tests  /p:CollectCoverage=true  /p:CoverletOutputFormat=lcov /p:SkipAutoProps=true  /p:ExcludeByAttribute="ExcludeFromCodeCoverage"
  - publishImageConfig:
      dockerfilePath: ./ops/dockerfile
      buildContext: .
      tag: hive:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./ops/k8s/deployment.yaml
timeout: 60
notification: {}
