stages:
- name: test
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile-Node.test
      buildContext: .
      tag: hive-node-test
  - publishImageConfig:
      dockerfilePath: ./Dockerfile-Dotnet.test
      buildContext: .
      tag: hive-dotnet-test
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        curl --retry 4 --retry-connrefused -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
        cd ./src/FrontEnd
        pnpm install
        pnpm test
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hive
      pushRemote: true
      registry: 10.1.0.34:5000
    env:
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
