stages:
- name: test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm i -g pnpm
        cd ./src/Hive.FrontEnd
        pnpm install
        pnpm test
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/sdk:6.0
      shellScript: |-
        cd ./src
        dotnet test ./Hive.Api.Tests -c Test /p:CollectCoverage=true /p:CoverletOutputFormat=json /p:CoverletOutputFormat=opencover /p:SkipAutoProps=true  /p:Exclude=[Hive.Domain]*
        dotnet test ./Hive.Domain.Tests /p:CollectCoverage=true  /p:CoverletOutputFormat=json /p:CoverletOutputFormat=opencover /p:SkipAutoProps=true
  - publishImageConfig:
      dockerfilePath: ./ops/dockerfile
      buildContext: .
      tag: hive:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.lab.sorijen.net.au
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./ops/k8s/deployment.yaml
timeout: 60
notification: {}
