stages:
- name: test
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile.test
      buildContext: .
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hive
      pushRemote: true
      registry: 10.1.0.34:5000
    env:
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
