stages:
- name: test
  steps:
  - publishImageConfig:
      dockerfilePath: ./ops/dockerfile
      buildContext: .
      tag: hive:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./ops/k8s/deployment.yaml
timeout: 60
notification: {}
