stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hive
      pushRemote: true
      registry: 10.1.0.34:5000/hive
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
