stages:
- name: test
  steps:
  - runScriptConfig:
      image: docker-registry/node/node:latest
      shellScript: |-
        curl  --retry 4 --retry-connrefused -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
        cd ./src/FrontEnd
        pnpm install
        pnpm test
  - runScriptConfig:
      image: docker-registry/dotnet/sdk:latest
      shellScript: |-
        cd ./src
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
  - publishImageConfig:
      dockerfilePath: ./ops/dockerfile
      buildContext: .
      tag: hive:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./ops/k8s/deployment.yaml
timeout: 60
notification: {}
