---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-deployment
  namespace: hive
  labels:
    app: hive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        app: hive
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: hive
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: production
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hive-staging
  namespace: hive
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sol@sorijen.net.au
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class:  nginx
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hive-prod
  namespace: hive
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sol@sorijen.net.au
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class:  nginx
---
kind: Service
apiVersion: v1
metadata:
  name: hive-service
  namespace: hive
spec:
  selector:
    app: hive
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: ClientIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: hive-prod
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
  name: hive-ingress
  namespace: hive
spec:
  rules:
    - host: sorhome.sorijen.net.au
      http:
        paths:
          - backend:
              service:
                name: hive-service
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - sorhome.sorijen.net.au
      secretName: hive-cert-prod-tls