kind: Service
apiVersion: v1
metadata:
  name: hive-service
  namespace: default
spec:
  selector:
    app: hive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-deployment
  labels:
    app: hive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        app: hive
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: hive
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80