kind: Service
apiVersion: v1
metadata:
  name: hive
  namespace: hive
spec:
  selector:
    app: hive
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive
  labels:
    app: hive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
    namespace: hive
    labels:
        app: hive
    spec:
      containers:
      - name: hive
        image: hive
        ports:
        - containerPort: 80