---
kind: Service
apiVersion: v1
metadata:
  name: hive-service
spec:
  selector:
    app: hive
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
  name: hive-ingress
spec:
  rules:
    - host: "hive.10.1.2.1.xip.io"
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /
          backend:
            serviceName: hive-service
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-deployment
  labels:
    app: hive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        app: hive
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: hive
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80