---
kind: Service
apiVersion: v1
metadata:
  name: hive-service
  namespace: hive
spec:
  selector:
    app: hive
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: ClientIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
    cert-manager.io/issuer: "letsencrypt-staging"
  name: hive-ingress
  namespace: hive
spec:
  rules:
    - host: "xip.io"
      http:
        paths:
        - backend:
            service:
              name: hive-service
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
    - host: "sorhome.sorijen.net.au"
      http:
        paths:
        - backend:
            service:
              name: hive-service
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-deployment
  namespace: hive
  labels:
    app: hive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        app: hive
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: hive
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production