format_version: 10
pipelines:
  Hive:
    group: Hive-Pipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-fddb0ac:
        git: https://git.lab.sorijen.net.au/spirallogic/hive.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          run-frontend-tests:
            timeout: 0
            elastic_profile_id: 'hive-agent'
            artifacts:
            - test:
                source: reports/**/*
                destination: reports
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    docker login -u silly -p login tcp://registry.lab.sorijen.net.au:443
                    docker build -t frontend-test-results:${GO_REVISION} -f ./ops/dockerfile.frontend.test .
                    docker run   --name frontend-tests-${GO_REVISION} frontend-test-results:${GO_REVISION}
                    docker cp frontend-tests-${GO_REVISION}:/source/reports ./reports
                    docker kill  frontend-tests-${GO_REVISION}
                    docker rm frontend-tests-${GO_REVISION}
                  shtype: bash
                run_if: passed
          run-backend-tests:
            timeout: 0
            elastic_profile_id: 'hive-agent'
            artifacts:
            - test:
                source: reports/**
                destination: testoutput
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    docker login -u silly -p login tcp://registry.lab.sorijen.net.au:443
                    docker build -t backend-test-results:${GO_REVISION} -f ./ops/dockerfile.backend.test .
                    docker run   --name backend-tests-${GO_REVISION} backend-test-results:${GO_REVISION}
                    docker cp backend-tests-${GO_REVISION}:/source/Hive.Domain.Tests/coverage.opencover.xml ./reports/domain-coverage.opencover.xml
                    docker cp backend-tests-${GO_REVISION}:/source/Hive.Api.Tests/coverage.opencover.xml ./reports/api-coverage.opencover.xml
                    docker kill  backend-tests-${GO_REVISION}
                    docker rm backend-tests-${GO_REVISION}
                  shtype: bash
                run_if: passed
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            elastic_profile_id: 'hive-agent'
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    docker build -t registry.lab.sorijen.net.au/hive:${GO_REVISION} -f ./ops/dockerfile .
                    docker login -u not -p needed registry.lab.sorijen.net.au
                    docker push registry.lab.sorijen.net.au/hive:${GO_REVISION}
                  shtype: bash
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        environment_variables:
          CICD_IMAGE: hive
        jobs:
          deploy:
            timeout: 0
            environment_variables:
              HIVE_SERVER: https://10.1.2.1:6443
            elastic_profile_id: 'hive-agent'
            tasks:
            - exec:
                arguments:
                - -c
                - docker
                command: bash
                run_if: passed
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    docker login -u not -p needed registry.lab.sorijen.net.au
                    echo ${GO_REVISION}
                  shtype: bash
                run_if: passed
