name: 'Hive Tests'
on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
      - '.gitea/**'
jobs:
  BackEnd:
    runs-on: ubuntu-22.04
    name: 'Back End - Tests'
    defaults:
      run:
        working-directory: './src'
    steps:
      - uses: actions/checkout@v4
      - name: Setup - dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('~/.nuget/packages/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install - dependencies
        run: dotnet restore
      - name: Test 
        run: |
            mkdir -p ${GITHUB_ACTION_PATH}/reports
            dotnet tool restore
            dotnet tool run dotnet-coverage collect --output-format cobertura dotnet test -c test ./
            dotnet tool run reportgenerator "-reports:./output.cobertura.xml" "-sourcedirs:./" "-assemblyfilters:+Hive.*;-*.Tests" "-targetdir:${GITHUB_ACTION_PATH}/reports"  -reporttypes:Html
            dotnet tool run dotnet-dotcover test -c Test --dcOutput=${GITHUB_ACTION_PATH}/reports/dotcover.html --dcReportType=HTML --dcHideAutoProperties "--dcFilters=+:Hive.*;-:*.Tests;-:function=.ctor"  ./
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: backend-reports
          path: |
            ./reports
          retention-days: 5
  FrontEnd:
    runs-on: ubuntu-22.04
    name: 'Front End - Lint - Tests'
    container:
      image: node:22-alpine
      env:
        CI: true
    defaults:
      run:
        working-directory: './src/Hive.FrontEnd/'
    steps:
      - uses: actions/checkout@v4
      - name: Sonar Scan
        run: | 
          cd src/Hive.FrontEnd
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install --frozen-lockfile
          pnpm test:all:report
          mv reports/* ${GITHUB_ACTION_PATH}/reports/
          sed -i "s~${GITHUB_ACTION_PATH}~${GITHUB_ACTION_PATH}/src/Hive.FrontEnd/src/~g" ${GITHUB_ACTION_PATH}/src/reports/frontend/lcov.info
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: frontend-reports
          path: |
            ./reports
          retention-days: 5
  sonar-scan:
    needs: [FrontEnd, BackEnd]
    runs-on: ubuntu-latest
    container:
      image: registry.lab.sorijen.net.au/build-image:latest
      env:
        SONARQUBE_KEY: ${secrets.SONARQUBE_KEY}
        LANG: en_US.UTF-8
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: reports
      - name: Sonar Scan
        run: | 
          sed -i "s~/reports~/drone/src~g" /drone/src/ops/SonarQube.Analysis.xml
          node -v
          java -version
          # - dotnet tool restore
          dotnet-sonarscanner begin /k:hive /s:ops/SonarQube.Analysis.xml /d:sonar.token=$SONARQUBE_KEY
          dotnet build ./src
          dotnet-coverage collect --output-format xml dotnet test src
          dotnet-sonarscanner end /d:sonar.token=$SONARQUBE_KEY