FROM golang:1.20-alpine as build
WORKDIR /source
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -installsuffix 'static'

FROM alpine
WORKDIR /app
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=build /source/drone-card-maker /app/drone-card-maker
RUN ln -s /app/drone-card-maker /usr/local/bin

CMD ["/app/drone-card-maker", "card.json"]