FROM mcr.microsoft.com/dotnet/sdk:8.0-preview-jammy
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_GENERATE_ASPNET_CERTIFICATE=true
ENV ASPNETCORE_URLS "https://+:5001;http://+:5000"

COPY --from=node:19-alpine /usr/lib /usr/lib
COPY --from=node:19-alpine /usr/local/share /usr/local/share
COPY --from=node:19-alpine /usr/local/lib /usr/local/lib
COPY --from=node:19-alpine /usr/local/include /usr/local/include
COPY --from=node:19-alpine /usr/local/bin /usr/local/bin

RUN npm install -g pnpm

WORKDIR /source
COPY ./src .

RUN pnpm install -C ./Hive.FrontEnd 
RUN dotnet build -c debug

EXPOSE 5000
EXPOSE 5001

ENTRYPOINT ["dotnet","run","-c","debug","--project","./Hive.Api"]
