FROM library/node:17 as node-build

WORKDIR /source
RUN chown -R node:node /source
USER node
COPY src/Hive.FrontEnd/package.json .

ENV NODE_ENV=production
RUN npm i --location=global pnpm
RUN pnpm install -P

COPY ./src/Hive.FrontEnd .
RUN pnpm vite:build

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS dotnet-build
WORKDIR /source

COPY ./src .
RUN dotnet restore
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Production

COPY --from=dotnet-build /app .
COPY --from=node-build /source/public ./wwwroot
ENTRYPOINT ["./Hive.Api"]
