FROM registry.lab.sorijen.net.au/build-image as build

WORKDIR /usr/src/frontend
ENV NODE_ENV=production

COPY src/Hive.FrontEnd/package.json src/Hive.FrontEnd/pnpm-lock.yaml ./
COPY ./src/Hive.FrontEnd/node_modules ./node_modules
RUN pnpm install -P --frozen-lockfile

COPY ./src/Hive.FrontEnd .
RUN pnpm vite:build

WORKDIR /usr/src/backend
ENV ASPNETCORE_ENVIRONMENT=Production

COPY ./src .
RUN dotnet publish -c release --property PublishDir=/usr/src/app

FROM mcr.microsoft.com/dotnet/aspnet:8.0.0-preview.3
WORKDIR /usr/src/app
ENV ASPNETCORE_ENVIRONMENT=Production

COPY --from=build /usr/src/app .
COPY --from=build /usr/src/frontend/public ./wwwroot
ENTRYPOINT ["./Hive.Api"]
