FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /source
COPY ./src .

RUN dotnet test ./Hive.Api.Tests -c Test /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov,json\" /p:SkipAutoProps=true  /p:Exclude=[Hive.Domain]*
RUN dotnet test ./Hive.Domain.Tests /p:CollectCoverage=true  /p:CoverletOutputFormat=\"opencover,lcov,json\" /p:SkipAutoProps=true
RUN dotnet add package ReportGenerator --version 5.0.0
RUN dotnet $(UserProfile)\.nuget\packages\reportgenerator\5.0.0\tools\net6.0\ReportGenerator.dll "-reports:./Hive.Api.Tests/coverage.opencover.xml" "-targetdir:api-coveragereport" -reporttypes:Html
RUN dotnet $(UserProfile)\.nuget\packages\reportgenerator\5.0.0\tools\net6.0\ReportGenerator.dll "-reports:./Hive.Domain.Tests/coverage.opencover.xml" "-targetdir:domain-coveragereport" -reporttypes:Html
