FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /source
COPY . .

RUN dotnet new tool-manifest
RUN dotnet tool install dotnet-reportgenerator-globaltool

RUN dotnet test /source/src/Hive.Domain.Tests -c Test /p:CollectCoverage=true  /p:CoverletOutputFormat=opencover /p:SkipAutoProps=true
RUN dotnet reportgenerator "-reports:/source/src/Hive.Domain.Tests/coverage.opencover.xml" "-targetdir:/source/domain-coverage" -reporttypes:Html
