FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /source
COPY . .

RUN dotnet new tool-manifest
RUN dotnet tool install dotnet-reportgenerator-globaltool

RUN dotnet test ./src/Hive.Api.Tests -c Test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:SkipAutoProps=true  /p:Exclude=[Hive.Domain]*
RUN dotnet reportgenerator "-reports:./src/Hive.Api.Tests/coverage.opencover.xml" "-targetdir:./api-coverage" -reporttypes:Html
