services:
  frontend:
    image: hive-frontend
    build:
      context: .
      dockerfile: ops/dockerfile.dev
      target: frontend
    volumes:
      - wwwroot:/source/public
    environment:
      - IS_DOCKER=true
    develop: 
      watch:
        - path: ./src/Hive.FrontEnd/package.json
          action: rebuild
        - path: ./src/Hive.FrontEnd/src
          action: sync
          target: /source/src
          ignore:
            - '**/node_modules/**'
  backend:
    image: hive-backend
    build:
      context: .
      dockerfile: ops/dockerfile.dev
      target: backend
    volumes:
      - wwwroot:/source/Hive.Api/wwwroot
      - ~/.aspnet/https:/https:ro
    ports:
      - 5001:5001
      - 5000:5000
    environment:
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
     - ASPNETCORE_Kestrel__Certificates__Default__Password=hive
     - ASPNETCORE_URLS=https://+:5001;http://+:5000
    develop: 
      watch:
        - path: ./src
          action: sync
          target: /source
          ignore:
            - '**/bin/**'
            - '**/obj/**'
            - './src/Hive.FrontEnd/**'
    depends_on:
      - 'redis'
      - frontend
  redis:
    container_name: redis
    image: library/redis:7-alpine
    volumes:
      - type: tmpfs
        target: /data
volumes: 
  wwwroot: