FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /source
COPY . .

RUN dotnet new tool-manifest || true
RUN dotnet tool install dotnet-reportgenerator-globaltool

RUN dotnet test --collect:"XPlat Code Coverage" ./src/Hive.Domain.Tests -c Test --settings ./src/Hive.Domain.Tests/runsettings.xml

RUN mkdir -p ./domain-coverage/

WORKDIR /source/src/Hive.Domain.Tests/TestResults

RUN mv **/coverage.opencover.xml /source/domain-coverage/

WORKDIR /source

RUN mv /source/domain-coverage/coverage.opencover.xml /source/domain-coverage/domain-coverage.opencover.xml

RUN dotnet reportgenerator "-reports:/source/domain-coverage/domain-coverage.opencover.xml" "-targetdir:/source/domain-coverage" -reporttypes:Html
