FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /source
COPY . .

RUN dotnet new tool-manifest || true
RUN dotnet tool install dotnet-reportgenerator-globaltool

RUN dotnet test ./src/Hive.Api.Tests -c Test --settings ./src/Hive.Api.Tests/runsettings.xml
RUN dotnet reportgenerator "-reports:./**/coverage.opencover.xml" "-targetdir:./api-coverage" -reporttypes:Html
RUN mv ./**/coverage.opencover.xml ./api-coverage/
RUN mv ./api-coverage/coverage.opencover.xml ./api-coverage/api-coverage.opencover.xml
