FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /source
COPY . .

RUN dotnet new tool-manifest || true
RUN dotnet tool install dotnet-reportgenerator-globaltool

RUN dotnet test ./src/Hive.Domain.Tests -c Test --settings ./src/Hive.Domain.Tests/runsettings.xml
RUN dotnet reportgenerator "-reports:./**/Hive.Domain.Tests/coverage.opencover.xml" "-targetdir:./domain-coverage" -reporttypes:Html
RUN mv ./**/coverage.opencover.xml ./domain-coverage/
RUN mv ./domain-coverage/coverage.opencover.xml ./domain-coverage/domain-coverage.opencover.xml
