format_version: 10
pipelines:
  hive-pipe:
    group: Hive-Pipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-24540d2:
        git: https://git.lab.sorijen.net.au/spirallogic/hive.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-frontend-tests:
            timeout: 0
            elastic_profile_id: hive-agent
            artifacts:
            - build:
                source: reports/**
                destination: ''
            - build:
                source: reports/__coverage__/lcov.info
                destination: coverage/
            - build:
                source: reports/__lint__/eslint.json
                destination: coverage/
            - build:
                source: reports/__lint__/eslint.test.json
                destination: coverage/
            - build:
                source: reports/__lint__/stylelint.json
                destination: coverage/
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    docker build -t frontend-test-results:${GO_PIPELINE_COUNTER} -f ./ops/dockerfile.frontend.test .
                    docker run --name frontend-tests-${GO_PIPELINE_COUNTER} frontend-test-results:${GO_PIPELINE_COUNTER}

                    docker cp frontend-tests-${GO_PIPELINE_COUNTER}:/source/src/Hive.FrontEnd/reports ./

                    docker rm frontend-tests-${GO_PIPELINE_COUNTER}
                    docker rmi frontend-test-results:${GO_PIPELINE_COUNTER}
                  shtype: sh
                run_if: passed
          run-api-tests:
            timeout: 0
            elastic_profile_id: hive-agent
            artifacts:
            - build:
                source: api-coverage/**
                destination: ''
            - build:
                source: api-coverage.opencover.xml
                destination: coverage/
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    docker build -t api-test-results:${GO_PIPELINE_COUNTER} -f ./ops/dockerfile.api.test .
                    docker run   --name api-tests-${GO_PIPELINE_COUNTER} api-test-results:${GO_PIPELINE_COUNTER}

                    docker cp api-tests-${GO_PIPELINE_COUNTER}:/source/api-coverage ./
                    docker cp api-tests-${GO_PIPELINE_COUNTER}:/source/src/Hive.Api.Tests/coverage.opencover.xml ./api-coverage.opencover.xml

                    docker stop api-tests-${GO_PIPELINE_COUNTER}
                    docker rm api-tests-${GO_PIPELINE_COUNTER}
                    docker rmi api-test-results:${GO_PIPELINE_COUNTER}
                  shtype: sh
                run_if: passed
          run-domain-tests:
            timeout: 0
            elastic_profile_id: hive-agent
            artifacts:
            - build:
                source: domain-coverage/**
                destination: ''
            - build:
                source: domain-coverage.opencover.xml
                destination: coverage/
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    docker build  -t domain-test-results:${GO_PIPELINE_COUNTER} -f ./ops/dockerfile.domain.test .
                    docker run  --name domain-tests-${GO_PIPELINE_COUNTER} domain-test-results:${GO_PIPELINE_COUNTER}

                    docker cp domain-tests-${GO_PIPELINE_COUNTER}:/source/domain-coverage ./
                    docker cp domain-tests-${GO_PIPELINE_COUNTER}:/source/src/Hive.Domain.Tests/coverage.opencover.xml ./domain-coverage.opencover.xml

                    docker stop domain-tests-${GO_PIPELINE_COUNTER}
                    docker rm domain-tests-${GO_PIPELINE_COUNTER}
                    docker rmi domain-test-results:${GO_PIPELINE_COUNTER}
                  shtype: sh
                run_if: passed
    - sonar:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          scan:
            timeout: 0
            environment_variables:
              SONARQUBE_URL: sonarqube.lab.sorijen.net.au
            secure_variables:
              SONARQUBE_KEY: AES:ZK2/8+IvbWQv0491bHyvzA==:FX4EInqV1xDHitTXxR1zpU9QlQDemU3tn3DI2b7h2b31DM1cMxrmkFDIfBeTe2qe
            elastic_profile_id: hive-agent
            tasks:
            - fetch:
                is_file: true
                source: coverage/api-coverage.opencover.xml
                destination: reports
                pipeline: hive-pipe
                stage: test
                job: run-api-tests
                artifact_origin: gocd
                run_if: passed
            - fetch:
                is_file: true
                source: coverage/domain-coverage.opencover.xml
                destination: reports
                pipeline: hive-pipe
                stage: test
                job: run-domain-tests
                artifact_origin: gocd
                run_if: passed
            - fetch:
                is_file: true
                source: coverage/lcov.info
                destination: reports
                pipeline: hive-pipe
                stage: test
                job: run-frontend-tests
                artifact_origin: gocd
                run_if: passed
            - fetch:
                is_file: true
                source: coverage/eslint.test.json
                destination: reports
                pipeline: hive-pipe
                stage: test
                job: run-frontend-tests
                artifact_origin: gocd
                run_if: passed
            - fetch:
                is_file: true
                source: coverage/eslint.json
                destination: reports
                pipeline: hive-pipe
                stage: test
                job: run-frontend-tests
                artifact_origin: gocd
                run_if: passed
            - fetch:
                is_file: true
                source: coverage/stylelint.json
                destination: reports
                pipeline: hive-pipe
                stage: test
                job: run-frontend-tests
                artifact_origin: gocd
                run_if: passed
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: docker build --build-arg SONARQUBE_KEY=${SONARQUBE_KEY}
                    -t dockerfile.net-jdk:${GO_PIPELINE_COUNTER}  -f ./ops/dockerfile.net-jdk
                    .
                  shtype: sh
                run_if: passed
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            elastic_profile_id: hive-agent
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    docker build -t registry.lab.sorijen.net.au/hive:${GO_PIPELINE_COUNTER} -f ./ops/dockerfile .
                    docker login -u hive -p hive registry.lab.sorijen.net.au
                    docker push registry.lab.sorijen.net.au/hive:${GO_PIPELINE_COUNTER}
                  shtype: sh
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          deploy:
            timeout: 0
            environment_variables:
              NAMESPACE: hive
              ARTIFACT_IMAGE: registry.lab.sorijen.net.au/hive
              KUBERNETES_SERVICE_HOST: https://10.1.2.2
              KUBERNETES_PORT_443_TCP_PORT: '6443'
            secure_variables:
              KUBE_TOKEN: AES:l10TUp6iI9E+loZ+spTWEw==:UCf+vlHB5iT4oUxgmCEZQ+taC5JGDElIb9PjQR0W6DjIbQZT24x+k/aOT8Ar+fh3F/YOTi89G80BiEeUS9UNI1THug+07o/0fYK+YlJrfi6JQ92Zcq4fgjXj+px0D8ITMAlAoZFUsNFW2msBb+KmLkLemnStOeergkEzNIjb0ceSOERw1Wp6HtxmpIqGuihoddWdTYWKbp8KJLmu66GnXsOqBIgdwulo3wpSlXXzskE20hjG7VBnOznWa65hsJsoVQmHnzBjIZFK8wH6EF6JVTbKe4lKot+IoyMukFkiVgjuL7oCMBVhskE9X4bQrCE0NxFMNrI0zNAmAH/l999Sabt3Ad9GPcHAnh0H2nkYGzhIlTaptCFbRzTaRvaTq0RKEyS+dYuDIda0syKFlxRhWVHwK9Cj8/UNRMlCON9mqhwJRq54RHenABXaAWHGZzS8pBjyWxg1ai2h4p+llRnBKH75khf+4Ml0gmAinUbUCVQvKB5e0tor30LEQUwWLcA23Odf3NH1lZ1MHS4axFAaaDaaVwLUIg3BVWkyYZtK4VvHXFzzZY/+bwHH9kNHcUzHkIysFp48lFhUG+tuv7TeWszyQ/nNvlQ1N2UZraIm8F/Ubczsg5M2D+6lnL5xizC0jVkVgP6mKPQQvizMPPGGsjwr6UgYUHvu7Al/YoaB5kVFdKc0lSo/wKJhmbDTJyG+DwQtXoPTI9buyxTvh8/Y/F586Ypk5HjhMVYpZ/HtQe81V/EXQcQPIrzjvRuI37Y2tKATS5tec7SfSJiQJYm0bVCkmhuF/C7pO0B5/uZ3/jI0SwzDJQ560wJswZ7so8aWRqu2RuSXYX9e7g+qyNDsWghcQKKiUSVLHCWUtz1kq4AQS+R84OOO7HcWHVyJO3FASLTxOg/0Ji/LM7ci3Gg8ESMosNj+cU67gR51qSTfvy4RHBfn5Ld3sNfAhn7TE/+/6+jCCcrkGKO3elaIY3NJ4Tcr4BhSJRP/84WPO3pn95uPFyTBMp9Ap2OMdW730803VI4Qv2Vx+Ez0keCN3fHmU7R8mrLfzLu0CDWEe/+vRGRurUJDuR4OHJ83aDrXOZCXbeKtyC+KMAZKdi/vbmsFdSDRkzzxWa2g6UgW30iuwXwXrxaILKheqCnWem/f89qlrMMprADQ1EBkt6XLmEw+u1KhQX4qZVSS1gG3oqaXCfKwiU6SConPNv7jcIZBA1JvkgEF7Fp9+uxuy4ejWt2p1mWSMI6dfvbUk0fokdqnvy45FSGQ1k3nItr/b8EGeWRm
            elastic_profile_id: hive-agent
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    sed -i "s~{image}~$ARTIFACT_IMAGE:$GO_PIPELINE_COUNTER~g" ops/k8s/deployment.yaml

                    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

                    chmod +x ./kubectl


                    cat ops/k8s/deployment.yaml


                    ./kubectl --token  $KUBE_TOKEN --insecure-skip-tls-verify --server $KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT -n $NAMESPACE apply --force -f ops/k8s/deployment.yaml
                  shtype: sh
                run_if: passed
