format_version: 10
pipelines:
  sonar-image-build:
    group: Hive-Pipeline
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git-7529a08:
        git: https://github.com/SpiralLogic/hive.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
      - sonar-builder:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            sonar-scanner-build:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    run_if: passed
