format_version: 10
pipelines:
  sonar-image-build:
    group: Hive-Pipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      sonar-image-build:
        git: https://git.lab.sorijen.net.au/spirallogic/hive.git
        shallow_clone: true
        auto_update: false
        branch: master
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            sonar-image-build:
              timeout: 0
              tasks:
                - plugin:
                    configuration:
                      id: script-executor
                      version: 0.3.0
                    options:
                      script: |-
                        docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry-proxy.lab.sorijen.net.au                        - -u
                        docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry.lab.sorijen.net.au
                        docker build --build-arg SONARQUBE_KEY=${SONARQUBE_KEY} \
                          -t registry.lab.sorijen.net.au/sonar-scanner:latest \
                          -t registry.lab.sorijen.net.au/sonar-scanner:${GO_PIPELINE_LABEL} \
                          -f ./ops/dockerfile.sonar .
                        docker push registry.lab.sorijen.net.au/sonar-scanner:latest
                        docker push registry.lab.sorijen.net.au/sonar-scanner:${GO_PIPELINE_LABEL}
          
