format_version: 10
pipelines:
  sonar-image-build:
    group: Hive-Pipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      REGISTRY_USER: hive
      REGISTRY_PASS: hive
    materials:
      git-197bbb2:
        git: https://git.lab.sorijen.net.au/spirallogic/hive.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
      - sonar:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            sonar-image-build:
              timeout: 0
              elastic_profile_id: hive-agent
              tasks:
                - plugin:
                    configuration:
                      id: script-executor
                      version: 0.3.0
                    options:
                      script: |-
                        docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry-proxy.lab.sorijen.net.au
                        docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry.lab.sorijen.net.au
                        docker build --compress \
                        -t registry.lab.sorijen.net.au/sonar-scanner:latest \
                        -t registry.lab.sorijen.net.au/sonar-scanner:${GO_PIPELINE_LABEL} \
                        -f ./ops/dockerfile.net-jdk .
                        docker push registry.lab.sorijen.net.au/sonar-scanner:latest
                        docker push registry.lab.sorijen.net.au/sonar-scanner:${GO_PIPELINE_LABEL}
                      shtype: sh
                    run_if: passed
