name: 'Hive Tests'
on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
jobs:
  BackEnd:
    runs-on: ubuntu-22.04
    name: 'Back End - Tests'
    defaults:
      run:
        working-directory: './src'
    steps:
      - uses: actions/checkout@v3
      - name: Setup - dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('~/.nuget/packages/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install - dependencies
        run: dotnet restore
      - name: Test 
        run: |
            mkdir ./reports
            dotnet tool restore
            dotnet tool run dotnet-coverage collect --output-format cobertura dotnet test -c test ./
            dotnet tool run reportgenerator "-reports:./output.cobertura.xml" "-sourcedirs:./" "-assemblyfilters:+Hive.*;-*.Tests" "-targetdir:./reports/backend"  -reporttypes:Html
            dotnet tool run dotnet-dotcover test -c Test --dcOutput=./reports/backend/dotcover.html --dcReportType=HTML --dcHideAutoProperties "--dcFilters=+:Hive.*;-:*.Tests;-:function=.ctor"  ./
      - name: Upload - Test results
        uses: actions/upload-artifact@v3
        with:
          name: backend-results
          path: |
            ./reports
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
  FrontEnd:
    runs-on: ubuntu-22.04
    name: 'Front End - Lint - Test'
    defaults:
      run:
        working-directory: './src/Hive.FrontEnd/'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true
      - name: Setup - pnpm
        run: npm install --location=global pnpm
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install - dependencies
        run: pnpm install
      - name: Lint fix - Frontend
        run: pnpm lint:fix
      - name: Test - Frontend
        run: pnpm test
      - name: Upload - Test results
        uses: actions/upload-artifact@v3
        with:
          name: frontend-results
          path: src/Hive.FrontEnd/reports/
        if: ${{ always() }}
