name: 'Hive Frontend Tests'
on: 
  push:
    paths:
    - 'src/FrontEnd/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    name: 'Front End Tests'
    defaults:
      run:
        working-directory: './src/FrontEnd/'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Installs
        run: pnpm install
      - name: Test
        run: pnpm test 
