name: 'Hive Domain'
on: 
  push:
    paths:
    - 'src/Domain/**'
jobs:
  domain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '5.0.x'
      - name: Build
        run: dotnet build
        working-directory: './src/Domain/Hive.Domain/'
      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
        shell: bash
        working-directory: './src/Domain/Hive.Domain.Tests/'
