name: 'Hive Tests'
on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
jobs:
  BackEnd:
    runs-on: ubuntu-22.04
    name: 'Back End - Tests'
    defaults:
      run:
        working-directory: './src'
    steps:
      - uses: actions/checkout@v3
      - name: Setup - dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install - dependencies
        run: dotnet restore
      #      - name: Update Nuget Packages
      #        run: ../ops/dotnet-update.sh
      - name: Test 
        run: |
            mkdir -p ./coverage
            dotnet test --collect:"XPlat Code Coverage" ./Hive.Api.Tests  -c Test --settings ./Hive.Api.Tests/runsettings.xml
            mv ./Hive.Api.Tests/TestResults/*/coverage.opencover.xml ./coverage/api-coverage.opencover.xml
            dotnet test --collect:"XPlat Code Coverage" ./Hive.Domain.Tests  -c Test --settings ./Hive.Domain.Tests/runsettings.xml
            mv ./Hive.Domain.Tests/TestResults/*/coverage.opencover.xml ./coverage/domain-coverage.opencover.xml
      - name: Upload - Test results
        uses: actions/upload-artifact@v3
        with:
          name: backend-results
          path: |
            ./src/coverage/api-coverage.opencover.xml
            ./src/coverage/domain-coverage.opencover.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: OpenCover Badge Generator Api
        uses: danpetitt/open-cover-badge-generator-action@v1.0.9
        with:
          path-to-opencover-xml: ./src/coverage/api-coverage.opencover.xml
          minimum-coverage: 75
          repo-token: ${{ secrets.CI_TOKEN }}
      - name: OpenCover Badge Generator Domain
        uses: danpetitt/open-cover-badge-generator-action@v1.0.9
        with:
          path-to-opencover-xml: ./src/coverage/domain-coverage.opencover.xml
          minimum-coverage: 75
          repo-token: ${{ secrets.CI_TOKEN }}
  FrontEnd:
    runs-on: ubuntu-22.04
    name: 'Front End - Lint - Test'
    defaults:
      run:
        working-directory: './src/Hive.FrontEnd/'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - name: Setup - pnpm
        run: npm install --location=global pnpm
#      - name: Install update checker
#        run: pnpm install -g npm-check-updates
#      - name: Update
#        run: pnpm up
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install - dependencies
        run: pnpm install
      - name: Lint fix - Frontend
        run: pnpm lint:fix
      - name: Test - Frontend
        run: pnpm test
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: github action lint fixes
      - name: Upload - Test results
        uses: actions/upload-artifact@v3
        with:
          name: frontend-results
          path: src/Hive.FrontEnd/reports/
        if: ${{ always() }}
