name: 'Hive Tests'
on:
  push:
    paths:
      - 'src/Api/**'
      - 'src/Domain/**'
      - 'src/FrontEnd/**'
      - '.github/**'
jobs:
  backend:
    runs-on: ubuntu-20.04	
    name: 'Back End Update - Build - Tests'
    defaults:
      run:
        working-directory: './src'
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.100-preview.3.21202.5'
      - name: Update Nuget Packages
        run: sh ./ops/dotnet-update.sh
      - name: Test Api
        run: dotnet test ./Api/Hive.Api.Tests -c Test  /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:SkipAutoProps=true  /p:ExcludeByAttribute="ExcludeFromCodeCoverage" /p:Exclude="[Hive.Domain]*"
      - name: Test Domain
        run: dotnet test ./Domain/Hive.Domain.Tests  /p:CollectCoverage=true  /p:CoverletOutputFormat=lcov /p:SkipAutoProps=true  /p:ExcludeByAttribute="ExcludeFromCodeCoverage"
  frontend:
    runs-on: ubuntu-20.04
    name: 'Front End Update - Lint - Build - Test'
    defaults:
      run:
        working-directory: './src/FrontEnd/'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          check-latest: true
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install update checker
        run: pnpm install -g npm-check-updates
      - name: Update
        run: pnpm -up -L 
      - name: Installs
        run: pnpm install
      - name: Lint
        run: pnpm run lint:src
      - name: Test
        run: pnpm test
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: lint + upgrades
        
