name: 'Hive Tests'
on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
jobs:
  BackEnd:
    runs-on: ubuntu-22.04
    name: 'Back End - Tests'
    defaults:
      run:
        working-directory: './src'
    steps:
      - uses: actions/checkout@v3
      - name: Setup - dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install - dependencies
        run: dotnet restore
      #      - name: Update Nuget Packages
      #        run: ../ops/dotnet-update.sh
      - name: Test - Api 
        run: dotnet test ./Hive.Api.Tests --logger "console;verbosity=detailed" --logger "trx;LogFilePrefix=testResults" --results-directory "./reports"  -c Test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:SkipAutoProps=true  /p:Exclude=[Hive.Domain]*
      - name: Test - Domain
        run: dotnet test ./Hive.Domain.Tests --logger "console;verbosity=detailed" --logger "trx;LogFilePrefix=testResults" --results-directory "./reports" /p:CollectCoverage=true  /p:CoverletOutputFormat=lcov /p:SkipAutoProps=true /p:ExcludeByAttribute="ExcludeFromCodeCoverage"
      - name: Upload - Test results
        uses: actions/upload-artifact@v3
        with:
          name: backend-results
          path: |
            src/reports/
            src/Hive.Api.Tests/coverage.opencover.xml
            src/Hive.Domain.Tests/coverage.opencover.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
  FrontEnd:
    runs-on: ubuntu-22.04
    name: 'Front End - Lint - Test'
    defaults:
      run:
        working-directory: './src/Hive.FrontEnd/'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - name: Setup - pnpm
        run: npm install --location=global pnpm
#      - name: Install update checker
#        run: pnpm install -g npm-check-updates
#      - name: Update
#        run: pnpm up
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install - dependencies
        run: pnpm install
      - name: Lint fix - Frontend
        run: pnpm lint:fix
      - name: Test - Frontend
        run: pnpm test
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: github action lint fixes
      - name: Upload - Test results
        uses: actions/upload-artifact@v3
        with:
          name: frontend-results
          path: src/Hive.FrontEnd/reports/
        if: ${{ always() }}
