name: 'Hive Tests'
on:
  push:
    paths:
      - 'src/Api/**'
      - 'src/Domain/**'
      - 'src/FrontEnd/**'
      - '.github/**'
jobs:
  backend:
    runs-on: ubuntu-20.04	
    name: 'Back End Tests'
    defaults:
      run:
        working-directory: './src'
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Test Api
        run: dotnet test ./Api/Hive.Api.Tests -c Test  /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:SkipAutoProps=true  /p:ExcludeByAttribute="ExcludeFromCodeCoverage" /p:Exclude="[Hive.Domain]*"
        working-directory: './src'
      - name: Test Domain
        run: dotnet test ./Domain/Hive.Domain.Tests  /p:CollectCoverage=true  /p:CoverletOutputFormat=lcov /p:SkipAutoProps=true  /p:ExcludeByAttribute="ExcludeFromCodeCoverage"
        working-directory: './src'
  frontend:
    runs-on: ubuntu-20.04
    name: 'Front End Tests'
    defaults:
      run:
        working-directory: './src/FrontEnd/'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          check-latest: true
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Installs
        run: pnpm install
      - name: Test
        run: pnpm test 
