name: 'Hive API'
on: 
  push:
    paths:
    - 'src/Api/**'
jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './src/Api/Hive.Api/'
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '5.0.x'
      - name: Build
        run: dotnet build
        working-directory: './src/Api/Hive.Api.Tests/'
      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
        working-directory: './src/Api/Hive.Api.Tests/'
        